### PR TITLE
Add config file functionality for multiple users at once.

### PR DESCRIPTION
**Pull request by jimthedev**
This allows you to use the app just the same as you do now, or you can pass it the -f option and it will look for hipfm.json which adds support for multiple users within the same node process. I added an example config file for convenience.

### CODE REVIEW

**Comment by jimthedev** [comment]
Just rebased so please re-clone this if you happen to have cloned it.

**Comment by jimthedev** [comment]
Screenshot from the Music channel with multiple users Multi-user sample output

**Comment by allanhortle** [comment]
Nora know's where it's at. Diggin' the Tune-Yards.

**Comment by jimthedev** [comment]
I know right?! Mine are all guilty pleasure tracks. Thanks for the merge!

On May 14, 2014, at 7:11 PM, Allan Hortle notifications@github.com wrote:

Nora know's where it's at. Diggin' the Tune-Yards.

—
Reply to this email directly or view it on
GitHubhttps://github.com/blueflag/HipFM/pull/1#issuecomment-43149561
.

**Pull request merged**
